#+ summary: Retrieves all the information about ILIAD Datastreams
#+ description: NOTE! make sure response content type is application/json
#+ endpoint: https://www.foodie-cloud.org/sparql?default-graph-uri=http://w3id.org/iliad/dataaset/jf-pilot-sample
#+ tags:
#+   - json
#+ method: GET
#+ pagination: 100
#+ endpoint_in_url: False
#+ transform: {
#+   "description": "?info",
#+   "$anchor": "description",
#+   "@iot.count": "?total",
#+   "@iot.nextLink": "?next_link",
#+   "value": {
#+     "@iot.id": "?id",
#+     "@iot.selfLink": "?id_link",
#+     "description": "?desc_info",
#+     "name": "?name",
#+     "observationType": "?obs_type",
#+     "unitOfMeasurement": {
#+       "symbol": "?unit_symbol",
#+       "name": "?unit_name",
#+       "definition": "?unit_definition",
#+     },
#+     "Observations@iot.navigationLink": "?obs_link",
#+     "ObservedProperty@iot.navigationLink": "?op_link",
#+     "Sensor@iot.navigationLink": "?sensor_link",
#+     "Thing@iot.navigationLink": "?thing_link",
#+   }
#+ }

PREFIX iliad-api: <https://w3id.org/iliad/api>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sosa:  <http://www.w3.org/ns/sosa/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>


SELECT DISTINCT ?info ?obs_property ?sensor ?total ?id_link ?obs_link ?op_link ?sensor_link ?thing_link ?obs_type ?desc_info ?unit_definition ?unit_symbol ?unit_name ?next_link ?name ?id ?_obp
WHERE {
    ?col a sosa:ObservationCollection ;
        sosa:observedProperty ?obs_property ;
        sosa:madeBySensor ?sensor ;
        sosa:hasMember ?s .
    ?s a sosa:Observation .
    BIND ("OGC SensorThings API - Datastreams" as ?info)
    BIND (STRAFTER(STR(?sensor), "sensor/") AS ?sensor_raw)
    BIND (STRAFTER(STR(?obs_property), "property/") AS ?obs_property_raw)
    FILTER (?obs_property_raw=?_obp)
    BIND (CONCAT(?sensor_raw, "-", ?obs_property_raw) AS ?id)
    BIND (CONCAT("The datastream of jellyFish Abundance by user sensor: ",?sensor_raw, " for observed property: ",?obs_property_raw) AS ?desc_info)
    BIND (CONCAT(?sensor_raw, ':', ?obs_property_raw) AS ?name)
    BIND (URI("http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_ComplexObservation") AS ?obs_type)
    BIND (URI("http://qudt.org/2.1/vocab/unit") AS ?unit_definition)
    BIND (URI("U") AS ?unit_symbol)
    BIND (URI("Unitless") AS ?unit_name)
    BIND (URI(CONCAT('https://w3id.org/iliad/api/v1.0/Datastreams(', ?id,')')) AS ?id_link)
    BIND (URI(CONCAT('https://w3id.org/iliad/api/v1.0/Datastreams(', ?id,')/Observations')) AS ?obs_link)
    BIND (URI(CONCAT('https://w3id.org/iliad/api/v1.0/Datastreams(', ?id,')/ObservedProperty')) AS ?op_link)
    BIND (URI(CONCAT('https://w3id.org/iliad/api/v1.0/Datastreams(', ?id,')/Sensor')) AS ?sensor_link)
    BIND (URI(CONCAT('https://w3id.org/iliad/api/v1.0/Datastreams(', ?id,')/Thing')) AS ?thing_link)
    {
        SELECT (count(*) as ?total) 
        WHERE { 
            SELECT DISTINCT ?sensor2 ?obs_property2
            WHERE{
                ?col a sosa:ObservationCollection ;
                sosa:observedProperty ?obs_property2 ;
                sosa:madeBySensor ?sensor2 .
                BIND (STRAFTER(STR(?obs_property2), "property/") AS ?obs_property_raw2)
                FILTER (?obs_property_raw2=?_obp)
            }  
        }
    }
    OPTIONAL { ?s ?p ?_page_integer } 
    BIND (URI(CONCAT('https://w3id.org/iliad/api/v1.0/Datastreams?$top=100&$skip=', (?_page_integer+1)*100)) AS ?next_link)
} 
GROUP BY ?sensor ?obs_property
ORDER BY ?id
