#+ summary: Retrieves all the information about specific ILIAD Datastream related to the Observation
#+ description: NOTE! make sure response content type is application/json
#+ endpoint: https://www.foodie-cloud.org/sparql?default-graph-uri=http://w3id.org/iliad/dataaset/jf-pilot-sample
#+ tags:
#+   - json
#+ method: GET
#+ endpoint_in_url: False
#+ transform: {
#+   "@iot.id": "?ds_id",
#+   "$anchor": "@iot.id",
#+   "@iot.selfLink": "?id_link",
#+   "description": "?desc_info",
#+   "name": "?name",
#+   "observationType": "?obs_type",
#+   "unitOfMeasurement": {
#+     "symbol": "?unit_symbol",
#+     "name": "?unit_name",
#+     "definition": "?unit_definition",
#+     },
#+   "Observations@iot.navigationLink": "?obs_link",
#+   "ObservedProperty@iot.navigationLink": "?op_link",
#+   "Sensor@iot.navigationLink": "?sensor_link",
#+   "Thing@iot.navigationLink": "?thing_link",
#+   }

PREFIX iliad-api: <https://w3id.org/iliad/api>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sosa:  <http://www.w3.org/ns/sosa/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?_obs ?ds_id ?id_link ?desc_info ?name ?obs_type ?unit_symbol ?unit_name ?unit_definition ?obs_link ?op_link ?sensor_link ?thing_link
WHERE {
    ?col a sosa:ObservationCollection ;
        sosa:observedProperty ?obs_property ;
        sosa:madeBySensor ?sensor ;
        sosa:hasMember ?s .
    ?s a sosa:Observation .
    BIND (URI(CONCAT('http://w3id.org/iliad/jellyfish/observation/', ?_obs)) AS ?obs_uri)
    FILTER (?s = ?obs_uri)
    BIND (STRAFTER(STR(?sensor), '/sensor/') AS ?sensor_id)
    BIND (STRAFTER(STR(?obs_property), '/property/') AS ?property_id)
    BIND (CONCAT(?sensor_id, '-', ?property_id) AS ?ds_id)
    BIND (CONCAT("The datastream of jellyFish Abundance by user sensor: ",?sensor_id, " for observed property: ",?property_id) as ?desc_info)
    BIND (CONCAT(?sensor_id, ':', ?property_id) AS ?name)
    BIND (URI("http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_ComplexObservation") AS ?obs_type)
    BIND (URI("http://qudt.org/2.1/vocab/unit") AS ?unit_definition)
    BIND (URI("U") AS ?unit_symbol)
    BIND (URI("Unitless") AS ?unit_name)
    BIND (URI(CONCAT('https://w3id.org/iliad/api/v1.0/Datastreams(', ?ds_id,')')) AS ?id_link)
    BIND (URI(CONCAT('https://w3id.org/iliad/api/v1.0/Datastreams(', ?ds_id,')/Observations')) AS ?obs_link)
    BIND (URI(CONCAT('https://w3id.org/iliad/api/v1.0/Datastreams(', ?ds_id,')/ObservedProperty')) AS ?op_link)
    BIND (URI(CONCAT('https://w3id.org/iliad/api/v1.0/Datastreams(', ?ds_id,')/Sensor')) AS ?sensor_link)
    BIND (URI(CONCAT('https://w3id.org/iliad/api/v1.0/Datastreams(', ?ds_id,')/Thing')) AS ?thing_link)
}
