#+ summary: Retrieves all the information about ILIAD HistoricalLocations
#+ description: NOTE! make sure response content type is application/json
#+ endpoint: https://www.foodie-cloud.org/sparql?default-graph-uri=http://w3id.org/iliad/dataaset/jf-pilot-sample
#+ tags:
#+   - json
#+ method: GET
#+ pagination: 100
#+ endpoint_in_url: False
#+ transform: {
#+   "description": "?info",
#+   "$anchor": "description",
#+   "@iot.count": "?total",
#+   "@iot.nextLink": "?next_link",
#+   "value": {
#+     "@iot.id": "?location",
#+     "@iot.selfLink": "?id_link",
#+     "time": "?time",
#+     "Locations@iot.navigationLink": "?locations_link",
#+     "Thing@iot.navigationLink": "?things_link",
#+     },
#+   }

PREFIX iliad-api: <https://w3id.org/iliad/api>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sosa:  <http://www.w3.org/ns/sosa/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wgs84:  <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dwc:  <http://rs.tdwg.org/dwc/terms/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX oim-jf:  <http://w3id.org/iliad/oim/jellyfish#>


SELECT ?time ?info ?location ?total ?things_link ?locations_link ?id_link ?_thing
WHERE {
    ?s a sosa:ObservationCollection ;
        sosa:madeBySensor ?sens ;
        sosa:resultTime ?res .
    BIND (URI(CONCAT('http://w3id.org/iliad/jellyfish/sensor/', ?_thing)) AS ?thing_uri)
    FILTER (?sens=?thing_uri)
    BIND ("OGC SensorThings API - HistoricalLocations" AS ?info)
    BIND (xsd:dateTime(?res) AS ?time)
    BIND (STRAFTER(STR(?s), '/observation/') AS ?obs_id)
    BIND (STRAFTER(STR(?sens), '/sensor/') AS ?sens_id)
    BIND (CONCAT(?obs_id, '-', ?sens_id) AS ?location)
    BIND (URI(CONCAT('https://w3id.org/iliad/api/v1.0/HistoricalLocations(', ?location,')')) AS ?id_link)
    BIND (URI(CONCAT('https://w3id.org/iliad/api/v1.0/HistoricalLocations(', ?location,')/Things')) AS ?things_link)
    BIND (URI(CONCAT('https://w3id.org/iliad/api/v1.0/HistoricalLocations(', ?location,')/Locations')) AS ?locations_link)
            {
        SELECT (count(*) as ?total) WHERE {
            SELECT DISTINCT ?x
            WHERE {
                ?x a sosa:ObservationCollection ;
                    sosa:madeBySensor ?sens2 .
                BIND (URI(CONCAT('http://w3id.org/iliad/jellyfish/sensor/', ?_thing)) AS ?thing_uri2)
                FILTER (?sens2=?thing_uri2)
            } }

    }
    OPTIONAL { ?s ?p ?_page_integer } 
    BIND (URI(CONCAT('https://w3id.org/iliad/api/v1.0/FeaturesOfInterest?$top=100&$skip=', (?_page_integer+1)*100)) AS ?next_link)
}
ORDER BY ?location